### ISSUE TITLE
Tablet no_redirect doesn't work

### ISSUE THREAD

**Issue by Karmalakas** [suncat2000/MobileDetectBundle#33]
``` yml
mobile_detect:
    redirect:
        mobile:
            is_enabled: true
            host: http://m.mysite.lt
            action: redirect_without_path
        tablet:
            is_enabled: true
            action: no_redirect
    switch_device_view: ~
```

Tried `is_enabled: false` also, but tablet still gets redirected to http://m.mysite.lt
