### ISSUE TITLE
Redirect is no working

### ISSUE THREAD

**Issue by guillaumemarcade** [suncat2000/MobileDetectBundle#47]
Hi!

I'm trying to make a redirection to a mobile site like in the usage example. My config.yml is a copy/paste of what's in the readme.

```
mobile_detect:
    redirect:
        mobile: 
            is_enabled: true
            host: http://mobilesite.local
            status_code: 301
            action: redirect
        tablet: ~
    switch_device_view: ~
```

But when I hit http://website.local nothing happens. I'm using User Agent Switcher Firefox extension to appear as a mobile browser.

The bundle seems well configured because when I use is_mobile() twig helper it detects me as a mobile.

Any idea? Thanks in advance.

Guillaume
