### ISSUE TITLE
Service not found

### ISSUE THREAD

**Issue by mllull** [suncat2000/MobileDetectBundle#61]
Hello guys.

I'm trying to work with this Bundle but it gets me errors. This is the error:

```
"PHP message: PHP Fatal error:  Uncaught exception 'Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException' with message 'You have requested a non-existent service "mobile_detect.mobile_detector"
```

I try this code in my suerver, but in my computer, the same code works fine. In my _config.yml_ I have this lines of code:

```
#app/conﬁg/conﬁg.yml
mobile_detect:
    redirect:
        mobile: ~
        tablet: ~
    switch_device_view: ~
```

Someone knows how to fix this error? My Symphony version is: 2.5.4
